version: '3'

services:
  reverse-proxy:
    image: traefik:v1.7 # The official Traefik docker image
    restart: always
    command: --docker --api
    ports:
      - "80:80"     # The HTTP port
      - "8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      #- ./acme.json:/acme.json
    labels:
        - "traefik.frontend.rule=Host:traefik.localhost"
        - "traefik.port=8080"

networks:
  default:
    external:
      name: proxy

