version: '3'

services:

    phpmyadmin:
        restart: always
        image: phpmyadmin/phpmyadmin
        ports:
            - "80"
        environment:
            - PMA_HOST=172.17.0.1
        networks:
            - proxy
            - internal
        labels:
            - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.docker.localhost`)"
            - "traefik.docker.network=proxy"

networks:
    proxy:
        external: true
    internal:
        external: false

