version: '3'

services:

    phpmyadmin-nginx:
        restart: always
        image: nginx:latest
        ports:
            - "80"
        volumes:
            - ./nginx-site.conf:/etc/nginx/conf.d/default.conf:ro
            - phpmyadmin_data:/var/www/html/:ro
        networks:
            - proxy
            - internal
        labels:
            - "traefik.frontend.rule=Host:phpmyadmin.docker.localhost"
            - "traefik.docker.network=proxy"

    phpmyadmin-fpm:
        restart: always
        image: phpmyadmin/phpmyadmin:fpm-alpine
        ports:
            - "9000"
        environment:
            - PMA_HOST=172.17.0.1
        volumes:
            - phpmyadmin_data:/var/www/html/
        networks:
            - internal
        labels:
            - "traefik.enable=false"

volumes:
    phpmyadmin_data:

networks:
    proxy:
        external: true
    internal:
        external: false

